### ISSUE TITLE
ESbuild lags behind (non-trivially) in producing gzip friendly output for large pacakges

### ISSUE THREAD

**Issue by pastelsky** [privatenumber/minification-benchmarks#10]
Thanks for publishing these benchmarks. I'm the author of bundlephobia (a tool developers use to find out minified and minzipped sizes of npm packages) and was contemplating on replacing Terser with ESBuild's minifier to shave a few seconds from build. 

Seeing this benchmark, I got the picture that ESBuild and Terser and neck to neck. However, this doesn't seem to be the case for large packages. While the minified size might still be comparable in some cases, the gzipped size difference between esbuild and terser can vary between 5%-9% — which one might consider non-trivial difference for minification.

Benchmarks after replacing Terser with ESBuild in Bundlephobia's webpack config, and after manually extracting out license-style comments —

| Package | Minified Terser | Minified ESBuild | Minzip Terser | Minzip ESBuild |
|---------|-----------------|------------------|---------------|-----------------|
| webpack |      2.48 MB     |    2.52 MB (+2%) |    650KB     |     683 KB (+5%)  |
| echarts |      957 KB     |      975 KB (+2%) |    304KB     |     316 KB (+4%) |
| antd    |       1.16 MB    |  1.27MB  (+9%)   |       345 KB  |     370 KB  (+7%) |
| victory (charts) |     518 KB    |   532 KB (+3%) |  130KB    | 140 KB (+8%) |

The results remain the same whether running esbuild minify through `esbuild-loader` or the ESBuild CLI on the webpack built bundle.

Is there anyway to capture this on the current page?

**Comment by privatenumber** [comment]
Thanks @pastelsky -- I love Bundlephobia! Thanks for you work on that :)

Sounds like what you're referring to is the "compressability" of the minified output, which I have a bullet-point for under "Methodology". This isn't a metric often looked at when evaluating a minifier but I agree it's an important factor in comparing minifiers.

There will always be a performance discrepancy across minifiers as long as they use different optimizations. By how much depends on the input code. eg. you can exaggerate the performance between Terser and esbuild by using more patterns that esbuild does not minify but Terser does.

Sorry if the communication mislead you -- I will update the README to make it clear that esbuild is not a drop-in replacement for Terser.

If you're looking for a faster Terser replacement for Bundlephobia, definitely subscribe to https://github.com/swc-project/swc/pull/1302 where the author of SWC and Terser are collaborating on a Rust implementation. Last I checked, [esbuild doesn't have any more plans](https://github.com/evanw/esbuild/issues/639#issuecomment-792033958) to improve minification.

I think the best a benchmark can do to highlight the differences is by adding more larger data samples. Feel free to open PRs to add more, or list them here and I will add them when I find time. They should be single-file though, so Webpack won't work, but these from your list will work:
- https://unpkg.com/echarts@5.0.2/dist/echarts.js
- https://unpkg.com/antd@4.15.0/dist/antd.js
- https://unpkg.com/victory@35.4.13/dist/victory.js

**Comment by kzc** [comment]
https://unpkg.com/victory@35.4.13/dist/victory.js is rather odd. Every bundled module is an `eval`'ed string block of webpack requires:

```js
/******/ ({

/***/ "../../../node_modules/d3-array/src/array.js":
/*!******************************************************************************!*\
  !*** /Users/boygirl/formidable/v/victory/node_modules/d3-array/src/array.js ***!
  \******************************************************************************/
/*! exports provided: slice, map */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"slice\", function() { return slice; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"map\", function() { return map; });\nvar array = Array.prototype;\n\nvar slice = array.slice;\nvar map = array.map;\n\n\n//# sourceURL=webpack://Victory//Users/boygirl/formidable/v/victory/node_modules/d3-array/src/array.js?");

/***/ }),
```

Perhaps it was produced with webpack's debug or development mode. While it can be (poorly) minified, I don't think it is representative of how typical production libraries or applications are bundled and probably should not be included in the benchmark.

**Comment by privatenumber** [comment]
Good catch @kzc ! Reported in https://github.com/FormidableLabs/victory/issues/1818

**Comment by ryan-roemer** [comment]
Oh my, yep -- we need to adjust that.

@boygirl suggest we do something like:

```js
config.devtool = false
```

in https://github.com/FormidableLabs/victory/blob/main/config/webpack/webpack.config.dev.js#L11

While we're there, I think we can probably remove the `SourceMapDevToolPlugin` in https://github.com/FormidableLabs/victory/blob/main/config/webpack/webpack.config.dev.js#L20-L22 since we don't actually publish source maps...

**Comment by privatenumber** [comment]
No more evals in victory: https://unpkg.com/victory@35.5.1/dist/victory.js

**Comment by privatenumber** [comment]
FYI I updated it to include antd, echarts, victory.

It might be because I upgraded esbuild to the latest, but the performance difference between esbuild and Terser seems a lot smaller now (2% at most minzipped).

I will close this when I update the README to mention that esbuild is not a drop in replacement for Terser.

**Comment by kzc** [comment]
Since we're on the topic of bundle sizes, the google-closure-compiler.advanced minified commonjs files [do not work correctly](https://github.com/privatenumber/minification-benchmarks/issues/14#issuecomment-830919437). Without test programs to verify the correctness of the minified bundles, the benchmark results have to be taken with a grain of salt.

**Comment by privatenumber** [comment]
Thanks @kzc, it's on my radar.

Looking to knock out some of these easier issues out first.

**Comment by privatenumber** [comment]
Closed via https://github.com/privatenumber/minification-benchmarks/commit/5aac6e5b313ae594cb5d3b2b248f7a7b3bedab3a
