### ISSUE TITLE
add https://github.com/tdewolff/minify

### ISSUE THREAD

**Issue by danny007in** [privatenumber/minification-benchmarks#13]

**Comment by privatenumber** [comment]
Wow didn't know about https://github.com/tdewolff/minify Thanks for sharing!

Will add soon

**Comment by privatenumber** [comment]
Looked into it again. Looks like they're not on npm and don't have a JS API yet. https://github.com/tdewolff/minify/issues/379

It's not a huge blocker, but requires work that I don't have time for right now.
