### ISSUE TITLE
Fixing the google-closure-compiler advanced mode

### ISSUE THREAD

**Issue by zarov** [privatenumber/minification-benchmarks#14]
The `ADVANCED` mode of the Closure Compiler is pretty strict, and any error make it fails. You'll need to provide sufficient information about all variables used in the library to minify in order to use it.

As you can't of course do that here, one (very) ugly way to avoid failure of minification would be to set the `jscomp_off` flag to `'*'` in [google-closure-compiler.advanced.js](https://github.com/privatenumber/minification-benchmarks/blob/master/lib/benchmark/minifiers/google-closure-compiler.advanced.js).

I tried running it and here are the results, however I didn't test each library to see if it works. What do you think about it?

### [d3 v6.7.0](https://www.npmjs.com/package/d3/v/6.7.0)
- Unminified size: `560.0 kB`
- Unminified Gzip size: `131.4 kB`

| Minifier                                                                                         |                    Minified size |                  Minzipped size |                         Time |
| :----------------------------------------------------------------------------------------------- | -------------------------------: | ------------------------------: | ---------------------------: |
| [google-closure-compiler.advanced](/lib/benchmark/minifiers/google-closure-compiler.advanced.js) | **<sup>🏆-54% </sup>`260.6 kB`** | **<sup>🏆-30% </sup>`92.8 kB`** | **<sup>🏆 </sup>`13 796ms`** |
----
### [jquery v3.6.0](https://www.npmjs.com/package/jquery/v/3.6.0)
- Unminified size: `288.6 kB`
- Unminified Gzip size: `85.1 kB`

| Minifier                                                                                         |                   Minified size |                  Minzipped size |                        Time |
| :----------------------------------------------------------------------------------------------- | ------------------------------: | ------------------------------: | --------------------------: |
| [google-closure-compiler.advanced](/lib/benchmark/minifiers/google-closure-compiler.advanced.js) | **<sup>🏆-70% </sup>`87.4 kB`** | **<sup>🏆-62% </sup>`32.5 kB`** | **<sup>🏆 </sup>`6 725ms`** |
----
### [lodash v4.17.21](https://www.npmjs.com/package/lodash/v/4.17.21)
- Unminified size: `544.1 kB`
- Unminified Gzip size: `97.3 kB`

| Minifier                                                                                         |                   Minified size |                  Minzipped size |                        Time |
| :----------------------------------------------------------------------------------------------- | ------------------------------: | ------------------------------: | --------------------------: |
| [google-closure-compiler.advanced](/lib/benchmark/minifiers/google-closure-compiler.advanced.js) | **<sup>🏆-89% </sup>`60.2 kB`** | **<sup>🏆-79% </sup>`20.9 kB`** | **<sup>🏆 </sup>`7 491ms`** |
----
### [moment v2.29.1](https://www.npmjs.com/package/moment/v/2.29.1)
- Unminified size: `173.9 kB`
- Unminified Gzip size: `36.5 kB`

| Minifier                                                                                         |                   Minified size |                  Minzipped size |                        Time |
| :----------------------------------------------------------------------------------------------- | ------------------------------: | ------------------------------: | --------------------------: |
| [google-closure-compiler.advanced](/lib/benchmark/minifiers/google-closure-compiler.advanced.js) | **<sup>🏆-72% </sup>`49.6 kB`** | **<sup>🏆-52% </sup>`17.6 kB`** | **<sup>🏆 </sup>`5 150ms`** |
----
### [react v17.0.2](https://www.npmjs.com/package/react/v/17.0.2)
- Unminified size: `72.1 kB`
- Unminified Gzip size: `19.5 kB`

| Minifier                                                                                         |                   Minified size |                 Minzipped size |                        Time |
| :----------------------------------------------------------------------------------------------- | ------------------------------: | -----------------------------: | --------------------------: |
| [google-closure-compiler.advanced](/lib/benchmark/minifiers/google-closure-compiler.advanced.js) | **<sup>🏆-65% </sup>`25.4 kB`** | **<sup>🏆-52% </sup>`9.4 kB`** | **<sup>🏆 </sup>`4 115ms`** |
----
### [terser v5.7.0](https://www.npmjs.com/package/terser/v/5.7.0)
- Unminified size: `869.4 kB`
- Unminified Gzip size: `174.5 kB`

| Minifier                                                                                         |                    Minified size |                   Minzipped size |                        Time |
| :----------------------------------------------------------------------------------------------- | -------------------------------: | -------------------------------: | --------------------------: |
| [google-closure-compiler.advanced](/lib/benchmark/minifiers/google-closure-compiler.advanced.js) | **<sup>🏆-58% </sup>`368.9 kB`** | **<sup>🏆-33% </sup>`118.5 kB`** | **<sup>🏆 </sup>`9 117ms`** |
----
### [three v0.124.0](https://www.npmjs.com/package/three/v/0.124.0)
- Unminified size: `1.2 MB`
- Unminified Gzip size: `249.0 kB`

| Minifier                                                                                         |                    Minified size |                   Minzipped size |                         Time |
| :----------------------------------------------------------------------------------------------- | -------------------------------: | -------------------------------: | ---------------------------: |
| [google-closure-compiler.advanced](/lib/benchmark/minifiers/google-closure-compiler.advanced.js) | **<sup>🏆-58% </sup>`527.6 kB`** | **<sup>🏆-41% </sup>`148.5 kB`** | **<sup>🏆 </sup>`12 824ms`** |
----
### [vue v2.6.12](https://www.npmjs.com/package/vue/v/2.6.12)
- Unminified size: `223.2 kB`
- Unminified Gzip size: `62.3 kB`

| Minifier                                                                                         |                   Minified size |                  Minzipped size |                        Time |
| :----------------------------------------------------------------------------------------------- | ------------------------------: | ------------------------------: | --------------------------: |
| [google-closure-compiler.advanced](/lib/benchmark/minifiers/google-closure-compiler.advanced.js) | **<sup>🏆-69% </sup>`71.3 kB`** | **<sup>🏆-55% </sup>`28.2 kB`** | **<sup>🏆 </sup>`5 966ms`** |

**Comment by danny007in** [comment]
create PR(Pull request)

**Comment by kzc** [comment]
> however I didn't test each library to see if it works

@privatenumber `minification-benchmarks` ought to run the generated minified libraries against test programs to determine whether they are valid.

I don't have the java runtime on my machine needed to run Google Closure Compiler, but I pasted the contents of `node_modules/lodash/lodash.js` into https://closure-compiler.appspot.com/home, and clicked the Advanced and Compile buttons, and then pasted the result into `lodash.closure-advanced.js`. This file was unable to run the sample verification code below unlike the other minified libraries could. `lodash.closure-simple.js` (used below) was also produced in a similar way using the Simple button in the Google Closure Compiler web app - and it did work correctly.

Here's a crude lodash library test harness:

```sh
#!/bin/sh
for i in \
    node_modules/lodash/lodash.js \
    lodash.uglify-js.js \
    lodash.terser.js \
    lodash.esbuild.js \
    lodash.closure-simple.js \
    lodash.closure-advanced.js \
    ; \
do
    echo
    # show library name and size
    wc -c $i
    # test this library in node - it should output "25" if successful
    CODE="var _=require('./$i');console.log(_.flow([_.add, x=>x*x])(2,3));"
    echo $CODE
    node -e "$CODE"
done
```

when it is run it produces:
```
  544098 node_modules/lodash/lodash.js
var _=require('./node_modules/lodash/lodash.js');console.log(_.flow([_.add, x=>x*x])(2,3));
25

   69674 lodash.uglify-js.js
var _=require('./lodash.uglify-js.js');console.log(_.flow([_.add, x=>x*x])(2,3));
25

   71408 lodash.terser.js
var _=require('./lodash.terser.js');console.log(_.flow([_.add, x=>x*x])(2,3));
25

   72841 lodash.esbuild.js
var _=require('./lodash.esbuild.js');console.log(_.flow([_.add, x=>x*x])(2,3));
25

   73570 lodash.closure-simple.js
var _=require('./lodash.closure-simple.js');console.log(_.flow([_.add, x=>x*x])(2,3));
25

   58456 lodash.closure-advanced.js
var _=require('./lodash.closure-advanced.js');console.log(_.flow([_.add, x=>x*x])(2,3));
TypeError: Cannot set property 'placeholder' of undefined
```
Each library benchmarked should have similar verification code to disqualify invalid minified libraries.

I didn't test swc and babel-minify.

**Comment by privatenumber** [comment]
Thanks for the tip @zarov. I tried `jscomp_off '*'` as suggested, and the results are [very impressive](https://github.com/privatenumber/minification-benchmarks/tree/google-closure-compiler-advanced-jscomp_off). It beats Uglify in 8 out of 11 tests.

I won't merge https://github.com/privatenumber/minification-benchmarks/pull/19 until the results are verified though. Thanks for checking @kzc. I'll see if I can add some tests soon.

**Comment by kzc** [comment]
`lodash.closure-advanced.js` in the test above failed because of property mangling in the commonjs bundle which broke the library's API.

Given the following commonjs library input:
```
exports.some_calculation = function(x, y){ return x * y }
```

google closure compiler with simple settings produces:
```
exports.some_calculation=function(a,b){return a*b};
```

and google closure compiler with advanced settings produces:
```
exports.g=function(a,b){return a*b};
```

The last result is indeed smaller, but it will not work correctly in a NodeJS application because it changed the library's API.

If you want to compare apples with apples and produce comparable sizes to the google-closure-compiler.advanced settings, just enable `--mangle-props` on uglify-js and terser to further reduce sizes:

```
$ uglify-js d3.js -mc | wc -c
  265371

$ uglify-js d3.js -mc --mangle-props | wc -c
  247041
```

In this case it produced a result that was 7.4% smaller. But the results are meaningless without tests to verify the minified libraries.

**Comment by privatenumber** [comment]
Ah gotcha. Thanks for looking into it @kzc I'll try to add tests anyway to make sure existing behavior is working fine.

**Comment by privatenumber** [comment]
I started uploading minified results to each [GH Action run](https://github.com/privatenumber/minification-benchmarks/actions/workflows/benchmark.yml).

Anyone can download them and verify the results.

**Comment by kzc** [comment]
Here's a script that verifies the minified bundles for d3, query, lodash, moment, react, three and victory. It can easily be extended to cover the other libraries.

Run the script `verify-bundle.sh` in an empty directory with the file `minification-results.zip`.

```bash
$ cat verify-bundle.sh
#!/bin/bash

rm -rf benchmark-all-minifiers-* benchmark-bundles
rm -rf package.json node_modules yarn.lock
echo '{"license": "MIT"}' > package.json
yarn add jsdom@16.6.0 object-assign@4.1.1 react@17.0.2 --silent

unzip -q minification-results.zip
mkdir benchmark-bundles
cp -f benchmark-all-minifiers-*/*.js benchmark-bundles/
cd benchmark-bundles

PASS=-pass-
FAIL=*FAIL*

verify_bundle() {
  for i in `echo $1`
  do
    RESULT=`echo $2 | sed "s@__MODULE__@./$i@g" | node 2>/dev/null`
    [ "$RESULT" = "`echo $3`" ] && echo -n $PASS || echo -n $FAIL
    echo " $i"
  done
}

verify_bundle "d3*.js" \
  "var d3=require('__MODULE__');JSDOM=require('jsdom').JSDOM;window=new JSDOM('').window;document=window.document;var svg=d3.select(document.body).append('svg').attr('width',100).attr('height',100);svg.append('circle').style('fill','green').attr('r',40).attr('cx',50).attr('cy',50);console.log(document.body.innerHTML);" \
  '<svg width="100" height="100"><circle style="fill: green;" r="40" cx="50" cy="50"></circle></svg>'

verify_bundle "jquery*.js" \
  "JSDOM=require('jsdom').JSDOM;window=new JSDOM('<p>hello</p><div id=d1>big</div><p>world</p>').window;document=window.document;var jquery=require('__MODULE__');console.log(jquery.grep([1,2,3,4,5],x=>x%2).join(''));" \
  "135"

verify_bundle "lodash-*.js" \
  "var _=require('__MODULE__');console.log(_.flow([_.add, x=>x*x])(2,3));" \
  "25"

verify_bundle "moment-*.js" \
  "console.log(require('__MODULE__').duration('9.22:23:24.25').asSeconds())" \
  "858204.25"

verify_bundle "react*.js" \
  "JSDOM=require('jsdom').JSDOM;window=new JSDOM('').window;document=window.document;var React=require('__MODULE__');class Hello extends React.Component{render(){return React.createElement('div',null,'Hello '+this.props.place)}}console.log(JSON.stringify(React.createElement(Hello,{place:'World'},null)));" \
  '{"key":null,"ref":null,"props":{"place":"World","children":null},"_owner":null,"_store":{}}'

verify_bundle "three*.js" \
  "var t=require('__MODULE__');console.log(JSON.stringify((new t.Vector2(3,4)).manhattanDistanceTo(new t.Vector2(11,38))))" \
  "42"

verify_bundle "victory*.js" \
  "JSDOM=require('jsdom').JSDOM;window=new JSDOM('').window;document=window.document;var V=require('__MODULE__'),R=require('react');console.log(JSON.stringify(R.createElement(V.VictoryPie, null).props.data))" \
  '[{"x":"A","y":1},{"x":"B","y":2},{"x":"C","y":3},{"x":"D","y":1},{"x":"E","y":2}]'
```

Results:
```
$ bash verify-bundle.sh
-pass- d3--esbuild.js
-pass- d3--google-closure-compiler.simple.js
*FAIL* d3--swc.js
-pass- d3--terser.js
-pass- d3--terser.no-compress.js
-pass- d3--uglify-js.js
-pass- d3--uglify-js.no-compress.js
-pass- jquery--babel-minify.js
-pass- jquery--esbuild.js
*FAIL* jquery--google-closure-compiler.advanced.js
-pass- jquery--google-closure-compiler.simple.js
-pass- jquery--swc.js
-pass- jquery--terser.js
-pass- jquery--terser.no-compress.js
-pass- jquery--uglify-js.js
-pass- jquery--uglify-js.no-compress.js
-pass- lodash--babel-minify.js
-pass- lodash--esbuild.js
*FAIL* lodash--google-closure-compiler.advanced.js
-pass- lodash--google-closure-compiler.simple.js
-pass- lodash--swc.js
-pass- lodash--terser.js
-pass- lodash--terser.no-compress.js
-pass- lodash--uglify-js.js
-pass- lodash--uglify-js.no-compress.js
-pass- moment--babel-minify.js
-pass- moment--esbuild.js
-pass- moment--google-closure-compiler.simple.js
-pass- moment--swc.js
-pass- moment--terser.js
-pass- moment--terser.no-compress.js
-pass- moment--uglify-js.js
-pass- moment--uglify-js.no-compress.js
-pass- react.development--babel-minify.js
-pass- react.development--esbuild.js
-pass- react.development--google-closure-compiler.simple.js
-pass- react.development--swc.js
-pass- react.development--terser.js
-pass- react.development--terser.no-compress.js
-pass- react.development--uglify-js.js
-pass- react.development--uglify-js.no-compress.js
-pass- three--babel-minify.js
-pass- three--esbuild.js
-pass- three--google-closure-compiler.simple.js
-pass- three--swc.js
-pass- three--terser.js
-pass- three--terser.no-compress.js
-pass- three--uglify-js.js
-pass- three--uglify-js.no-compress.js
-pass- victory--esbuild.js
-pass- victory--google-closure-compiler.simple.js
*FAIL* victory--swc.js
-pass- victory--terser.js
-pass- victory--terser.no-compress.js
-pass- victory--uglify-js.js
-pass- victory--uglify-js.no-compress.js
```
Failure summary:
```
*FAIL* d3--swc.js
*FAIL* jquery--google-closure-compiler.advanced.js
*FAIL* lodash--google-closure-compiler.advanced.js
*FAIL* victory--swc.js
```

`google-closure-compiler.advanced.js` should be removed from the benchmark until the correct minification settings are provided.

`swc` also had a couple of failures that ought to be noted in `readme.md`.

**Comment by kzc** [comment]
The two `swc` failures above were due to that minifier inserting `var regeneratorRuntime=require("regenerator-runtime")` into the bundle.  This was not introduced by any other minifier:

```
$ grep -nl regenerator-runtime benchmark-bundles/*.js
benchmark-bundles/antd--babel-minify.js
benchmark-bundles/antd--esbuild.js
benchmark-bundles/antd--google-closure-compiler.simple.js
benchmark-bundles/antd--swc.js
benchmark-bundles/antd--terser.js
benchmark-bundles/antd--terser.no-compress.js
benchmark-bundles/antd--uglify-js.js
benchmark-bundles/antd--uglify-js.no-compress.js
benchmark-bundles/bundle.min--swc.js
benchmark-bundles/d3--swc.js
benchmark-bundles/victory--swc.js
```

The `antd` library's original source code happened to require `"./node_modules/regenerator-runtime/runtime.js"`, so it appears in all of its minified versions.  Not sure what `bundle.min` is.

If the `regenerator-runtime` module is added to the verify script then `swc` will run all tests successfully:
```
yarn add regenerator-runtime@0.13.7 --silent
```
Perhaps the `swc` minifier was not configured correctly?  It's unusual for a minifier to introduce new commonjs `require` statements.

**Comment by privatenumber** [comment]
I actually haven't had the chance to look into this yet 😅, but swc was upgraded with much improved minification [here](https://github.com/privatenumber/minification-benchmarks/pull/22) so those regenerator problems may not be happening anymore.

**Comment by kzc** [comment]
Verifying the build artifacts from https://github.com/privatenumber/minification-benchmarks/pull/22 ...

All google-closure-compiler.advanced results still do not work due to property mangling breaking the library APIs, and swc produces several invalid javascript bundles that cannot be parsed due to invalid identifier mangling:

```
$ bash verify-bundle.sh 
-pass- d3--esbuild.js
-pass- d3--google-closure-compiler.simple.js
*FAIL* d3--swc.js
-pass- d3--terser.js
-pass- d3--terser.no-compress.js
-pass- d3--uglify-js.js
-pass- d3--uglify-js.no-compress.js
-pass- jquery--babel-minify.js
-pass- jquery--esbuild.js
*FAIL* jquery--google-closure-compiler.advanced.js
-pass- jquery--google-closure-compiler.simple.js
*FAIL* jquery--swc.js
-pass- jquery--terser.js
-pass- jquery--terser.no-compress.js
-pass- jquery--uglify-js.js
-pass- jquery--uglify-js.no-compress.js
-pass- lodash--babel-minify.js
-pass- lodash--esbuild.js
*FAIL* lodash--google-closure-compiler.advanced.js
-pass- lodash--google-closure-compiler.simple.js
*FAIL* lodash--swc.js
-pass- lodash--terser.js
-pass- lodash--terser.no-compress.js
-pass- lodash--uglify-js.js
-pass- lodash--uglify-js.no-compress.js
-pass- moment--babel-minify.js
-pass- moment--esbuild.js
-pass- moment--google-closure-compiler.simple.js
*FAIL* moment--swc.js
-pass- moment--terser.js
-pass- moment--terser.no-compress.js
-pass- moment--uglify-js.js
-pass- moment--uglify-js.no-compress.js
-pass- react.development--babel-minify.js
-pass- react.development--esbuild.js
-pass- react.development--google-closure-compiler.simple.js
-pass- react.development--swc.js
-pass- react.development--terser.js
-pass- react.development--terser.no-compress.js
-pass- react.development--uglify-js.js
-pass- react.development--uglify-js.no-compress.js
-pass- three--babel-minify.js
-pass- three--esbuild.js
-pass- three--google-closure-compiler.simple.js
-pass- three--terser.js
-pass- three--terser.no-compress.js
-pass- three--uglify-js.js
-pass- three--uglify-js.no-compress.js
-pass- victory--esbuild.js
-pass- victory--google-closure-compiler.simple.js
-pass- victory--terser.js
-pass- victory--terser.no-compress.js
-pass- victory--uglify-js.js
-pass- victory--uglify-js.no-compress.js
```
```
$ acorn benchmark-all-minifiers-1627775732472/lodash--swc.js --module --ecma2019 --silent && echo ok
Unexpected keyword 'if' (benchmark-all-minifiers-1627775732472/lodash--swc.js 1:13236)

$ acorn benchmark-all-minifiers-1627775555549/d3--swc.js --module --ecma2019 --silent && echo ok
Unexpected keyword 'if' (benchmark-all-minifiers-1627775555549/d3--swc.js 1:24420)

$ acorn benchmark-all-minifiers-1627775707542/jquery--swc.js --module --ecma2019 --silent && echo ok
Unexpected keyword 'if' (benchmark-all-minifiers-1627775707542/jquery--swc.js 1:33914)

$ acorn benchmark-all-minifiers-1627775757996/moment--swc.js --module --ecma2019 --silent && echo ok
Unexpected keyword 'if' (benchmark-all-minifiers-1627775757996/moment--swc.js 1:26604)
```

Examples of swc failures:
```
a,hf=pe.isFinite,if=Ae.join
```
```
function if(ia,X){if(X!=null){var A,jf,ma=Le;if(Me[ia]!=null&&Me[ia].parentLocale!=null){Me[ia].set(la(Me[ia]._config,X));}else{jf=Ze(ia);if(jf!=null){ma=jf._config;}X=la(ma,X);if(jf==null){X.abbr=ia;}A=new oa(X);A.parentLocale=Me[ia];Me[ia]=A;}cf(ia);}else{if(Me[ia]!=null){if(Me[ia].parentLocale!=null){Me[ia]=Me[ia].parentLocale;if(ia===cf()){cf(ia);}}else if(Me[ia]!=null){delete Me[ia];}}}return Me[ia];}
```

**Comment by kzc** [comment]
The benchmarks results are dubious if known failures are included. Feel free to run and extend the verify script to all libraries.

Unsubscribing.

**Comment by privatenumber** [comment]
Thanks so much for your contributions @kzc.

The syntax errors have now validated as of #24.

Will make sure specific tests are added to each artifact before closing this.

**Comment by privatenumber** [comment]
Closing because:
- The primary request did not improve Google closure compiler advanced mode results
- The secondary request has been fulfilled in #26
