### ISSUE TITLE
SWC minifier broken due to a commit

### ISSUE THREAD

**Issue by kdy1** [privatenumber/minification-benchmarks#159]
https://github.com/privatenumber/minification-benchmarks/commit/4e48512ae24fc6f55db8ae73988153586fee367a

<img width="734" alt="image" src="https://user-images.githubusercontent.com/29931815/170092334-10d4d8de-f730-4b26-ba0e-9c25cb59000d.png">

I checked out the parent commit and updated `@swc/core` to `v1.2.189` and it works

**Comment by privatenumber** [comment]
Fixed in https://github.com/privatenumber/minification-benchmarks/commit/042d2168dc9a4054b9a52efe5466df553e63f682

Thanks for the heads up
