### ISSUE TITLE
Google closure compiler

### ISSUE THREAD

**Issue by ErDmKo** [privatenumber/minification-benchmarks#168]
It looks like you don't use compilation_level - ADVANCED_OPTIMIZATIONS for Google closure compiler case
https://developers.google.com/closure/compiler/docs/api-tutorial3
I think because of this this compiler is not best of all in terms of code compression )

**Comment by privatenumber** [comment]
It's been disabled because it was always failing:
https://github.com/privatenumber/minification-benchmarks/pull/28

Feel free to open a PR if you know how to fix it
