### ISSUE TITLE
stop using bina if possible

### ISSUE THREAD

**Issue by SArpnt** [privatenumber/minification-benchmarks#196]
the program is extremely buggy, it couldn't install to my working directory because there were spaces in the name, and `npx bina --help` throws an error message despite `npx bina` saying to use `bina --help`
it also has terrible security practices, like relying on the bina.egoist.sh domain to run a shell script without any verification whatsoever, when really it should just be part of the npm package

i'm assuming bina is only used for the postinstall to install tdewolff/minify, this seems unneccecary considering minify has an npm package.
it mentions to use `npm i @tdewolff/minify` for javascript bindings on the github readme

**Comment by privatenumber** [comment]
RE: `npm i @tdewolff/minify`
See https://github.com/tdewolff/minify/issues/519

For any other issues with bina, please report to https://github.com/egoist/bina

I'm closing this because this doesn't seem actionable in this repository. If you want to re-open, please propose an alternative.
