### ISSUE TITLE
are github actions accurate for testing performance?

### ISSUE THREAD

**Issue by SArpnt** [privatenumber/minification-benchmarks#197]
from the readme:
> Benchmarks are gathered on every PR via [GitHub Actions](https://github.com/privatenumber/minification-benchmarks/actions/workflows/benchmark.yml) (verifiable minified artifacts are uploaded on each run)

i'd expect that because github actions has varying use throughout the day that the performance varies massively and could spike and dip at any time. it's possible this is a useful metric for other people that need to run minification fast on github actions but generally performance is more often looked into by people minifying on their own machines, whether that's during testing, a local build step before uploading to a server, or automating a build step on a personal weak server.

maybe this repository should try benchmarking on user hardware? it probably wouldn't get updates as fast but would likely be much more useful to have benchmarks done on things like raspberry pis, desktops, old laptops, etc.

**Comment by privatenumber** [comment]
Not sure if I see value in that.

Benchmark speed is only one of three metrics; the other two metrics are not affected by environment. Three minifiers perform under 1s in most results. If speed is what the viewer is comparing, it would be a pretty negligible difference.

There are also so many variables that can affect CPU time, especially the input code itself. Trying show results for each environment would be an endless pursuit. If anyone wants accurate benchmarks, the best way is for them to run it themselves with their own machine and input code.

What's important to measure how the minifiers compare against each other, which can be done on any system as long as all minifiers are running on the same one.

**Comment by SArpnt** [comment]
the multipliers are more relevant than the times themselves, and with values often around a 100x difference there are plenty of cases where it matters.

if you want people to test on their own systems, that's perfectly valid, but it would probably help to add a bit more information to the readme and possibly instructions on how to get it running in case it might not be clear to some users. i could work on a pull request with these changes if you want since i need to get it set up anyways
