### ISSUE TITLE
minify/tdewolff says TypeError but can't reproduce

### ISSUE THREAD

**Issue by tdewolff** [privatenumber/minification-benchmarks#276]
Hi @privatenumber , what do you use to verify the validity of the minification output? It says "TypeError" for all minify/tdewolff outputs, but loading the minified output in Firefox or Chrome works fine (no errors), and putting it in ESLint gives no relevant errors (tested with `moment.js`).

Is the library outdated? Have you tried using https://www.npmjs.com/package/@tdewolff/minify?

**Comment by privatenumber** [comment]
It seems to be using version 0.5.2.

There's work to update to the npm registry in https://github.com/privatenumber/minification-benchmarks/pull/234, but it's blocked due to an unrelated problem.

**Comment by privatenumber** [comment]
To unblock the PR, I did a quick patch on my end to convert it back to CommonJS:
```js
// https://nodejs.org/api/esm.html#no-native-module-loading
const { string, config, file } = require('node-gyp-build')(__dirname);

// Starting from node 16, json imports have been unflagged
// import pkg from "./package.json" assert { type: "json" }
const version = require('@tdewolff/minify/package.json').version;

module.exports = {
	string,
	config,
	file,
	version,
};
```

Was there a reason your package needs to be in `module` mode?

Using a CommonJS module might be something you want to consider as the file is just re-exporting via `require()`.

**Comment by tdewolff** [comment]
Thanks for the quick fix, and amazing the improvement in speed!

Regarding modules, it is my understanding that ES modules is the new standard way and that CommonJS modules is specific to NodeJS? If this is not the case I can convert it to a CommonJS module, there is no specific need from the library, just trying to be up-to-date with technology ;-)

**Comment by privatenumber** [comment]
No problem and congrats on the fastest minifier!

ESM is the new standard but it's negated if only used to `createRequire` and create a CommonJS dependency.
I would keep it CommonJS unless you can figure out how to load `tdewolff-minify` without using any CommonJS.

**Comment by tdewolff** [comment]
Not exactly sure what you mean, it seems to me that loading with ESM works well: https://github.com/tdewolff/minify/blob/master/bindings/js/test/index.js. But to be honest I don't know much about the subject...

**Comment by privatenumber** [comment]
Yes, it works, but I'm saying there's no benefit to using ESM because you do `require()` via `createRequire` instead of `import`.

Changing it to CommonJS (code snippet I posted above) will also still be loadable from ESM because ESM cam parse CommonJS exports.
