### ISSUE TITLE
swc does not support minification yet

### ISSUE THREAD

**Issue by kdy1** [privatenumber/minification-benchmarks#6]
The option exists, but it's there because of future plan.
The only thing swc does and which is similar to minification is skipping comments and some whitespaces.

I'm porting terser to rust at https://github.com/swc-project/swc/pull/1302
I think swc should be added to the list after it's implemented.

And `swc.transform` applies (really) lots of compatibility transforms, as swc reimplements features of babel.
I'm going to add `swc.minify` with the PR I mentioned, so it should be used instead of `swc.transform`.

**Comment by privatenumber** [comment]
Good to know it currently only does comment/whitespace removal but that there's plan for more!

FYI swc is already on the list (added this morning) but I'll update when the minification improvements are in.

Looking forward to the improvements!

**Comment by kdy1** [comment]
I implemented the minifier. Can you try it?

**Comment by privatenumber** [comment]
Keeping this open until the benchmarks are updated

**Comment by kdy1** [comment]
Currently, it has a serious performance bug (infinite loop)
I'm now working on it.

**Comment by privatenumber** [comment]
I just merged in #22 which runs the new swc minification with [the following settings](https://github.com/privatenumber/minification-benchmarks/blob/master/scripts/minifiers/swc.js).

It fails on 5 of the artifacts though, so seems there's more work to be done but the improvements are very promising to say the least. 🔥

Thank you so much for working on it 🙌

**Comment by privatenumber** [comment]
@kdy1 

I added a [parsing check for syntax errors](https://github.com/privatenumber/minification-benchmarks/pull/24), and turns out swc is actually failing for all artifacts except react.

**Comment by kdy1** [comment]
It's a know issue and please update `@swc/core`

**Comment by privatenumber** [comment]
I upgraded to 1.2.71 but seems the errors still persist.

**Comment by kdy1** [comment]
Can you point me to the problematic output?

**Comment by privatenumber** [comment]
It's documented [here](https://github.com/privatenumber/minification-benchmarks/issues/14#issuecomment-890460579).

You can also clone this repo, and run:
```
npm run benchmark -- --minifier swc node_modules/vue/dist/vue.runtime.common.dev.js
```

Here are the swc.minify options:
https://github.com/privatenumber/minification-benchmarks/blob/bd29fcde47bc3312fad23e6ff4ed2040037a96d7/lib/minifiers/swc.js#L4-L8

**Comment by kdy1** [comment]
Oh, I forgot excluding `if` from name mangler. AST compressor is tested heavily, but name mangler is not.. So I need a better testing system.

**Comment by kdy1** [comment]
Thanks for reporting!
