### ISSUE TITLE
latest uglify-js release appears to minify all benchmarks correctly

### ISSUE THREAD

**Issue by kzc** [privatenumber/minification-benchmarks#8]
`uglify-js` supports ES6+ syntax now up to ES2020 and appears to minify the two libraries that previously failed:

```
$ node_modules/uglify-js/bin/uglifyjs -V
uglify-js 3.13.1

$ node_modules/uglify-js/bin/uglifyjs node_modules/d3/dist/d3.js -mc | wc -c
  267653

$ node_modules/uglify-js/bin/uglifyjs node_modules/terser/dist/bundle.min.js -mc | wc -c
  407144
```

Might you be able to update this benchmark to the latest release of `uglify-js`?

```patch
--- a/package.json
+++ b/package.json
@@ -41 +41 @@
-               "uglify-js": "^3.12.5",
+               "uglify-js": "^3.13.1",
```

Unfortunately I'm not running pnpm so I can't give you a PR.

Thanks in advance.

**Comment by privatenumber** [comment]
Thanks for the tip! Updated

**Comment by kzc** [comment]
@privatenumber This readme comment is also out of date:

> UglifyJS takes first place for minification performance. This is quite impressive as it doesn't support or leverage new and concise ES6+ syntax (hence the failed minifications for "terser v5.5.1").

No failed minification and it now handles ES6+ up to ES2020.

It is still written in ES5 though.

**Comment by privatenumber** [comment]
Ah good catch! Forgot to update. Fixed in https://github.com/privatenumber/minification-benchmarks/commit/b74b988441da93b339a6a093d6696089295dcfec

Thanks again for the info!

BTW, I see you're a major contributor of UglifyJS—is there a CHANGELOG or release notes for UglifyJS to keep updated with these new features?

**Comment by kzc** [comment]
Thanks.

Just the commit log and the README. The project is rather low key.
